# Generated by Django 2.0.6 on 2020-10-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.ImageField(default='pic/1.jpg', upload_to='pic'),
        ),
    ]
