# Generated by Django 2.0.6 on 2020-10-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo01', '0003_auto_20201030_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ImageField(default='pic/pic1.jpg', upload_to='pic/'),
        ),
    ]
